const actionTypes = {
  GET_LIST_ITEM: 'GET_LIST_ITEM',
  TODO_COUNT: 'TODO_COUNT',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TOGGLE_ITEM: 'TOGGLE_ITEM',
  ERROR: 'ERROR',
  UPDATE_DATA: 'UPDATE_DATA',
  MODIFY_ITEM: 'MODIFY_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM'
}

export {actionTypes}